on: [push]
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build image
      uses: mamezou-tech/buildpacks-action@master
      with:
        image: 'calculator-app'
        tag: '1.0.0'
        path: '/app'
        builder: 'pack build example --builder paketobuildpacks/builder:full'
        
    - name: Push image
